### ISSUE TITLE
Source is not buildable anymore!

### ISSUE THREAD

**Issue by hshahdoost** [cafebazaar/TrivialDrive#11]
Due to the fact that Android Studio uses gradle files to build projects and this source doesn't have any, We cannot build it anymore. Please add gradle build files.

**Comment by arg1998** [comment]
this project is not for any particular IDE , you should Copy files and packages in your project, read this link , help you to  set up your project in android studio 
http://developers.cafebazaar.ir/fa/docs/iab/implementation/

**Comment by hshahdoost** [comment]
@arg1998 Thanx for answering, I knew about the link, But what I was referring to was the fact that the concept of Project should be either a Library or an App which in both cases we should be able to build it in our system after cloning (Using a build script which should already be in the source). this project doesn't have any of that though it doesn't take much time to create a gradle.build file they have taken even longer time writing down a tutorial on how to build the app and use the libraries. All I'm saying is that since it is on github it's best if it could follow the open source project rules.
