### ISSUE TITLE
bindService returns false on some devices

### ISSUE THREAD

**Issue by alleece** [cafebazaar/TrivialDrive#13]
in IabHelper.java when we try to connect to inapp service using context.bindService() it returns false meaning failure.  Devices that have this issue seem to be mostly huawei phones running android api level 24.

**Comment by atilazz** [comment]
Yes, i have same issue in my applications.
Cafebazaar developer teams seem's can't solve this problem after two years i contact with support team.

**Comment by alleece** [comment]
This issue is due to battery limitation set on some devices. Go to settings, battery, [cloase apps after lock] or something like this. if you set market to close this raises thsi error.

این مشکل مربوط به محدودیت های روی تنظیمات باتری گوشی است.

**Comment by alleece** [comment]
روی هاواوی یک گزینه شبیه به این هست:
Settings/battery/close apps after...
باید چک کنید نام مارکت تیک نخورده باشد.

**Comment by shayanpourvatan** [comment]
This issue fixed in last version of SDK/Bazaar, We try to provide documentation ASAP.
