### ISSUE TITLE
آپدیت کنید

### ISSUE THREAD

**Issue by mehrdadmmb2** [cafebazaar/TrivialDrive#16]
کتابخونه مال 6سال پیشه 
به نظرتون الان وقتش نیست که آپدیتش کنید و یه ورژن مخصوص اندروید استادیو ارائه کنید؟

**Comment by arash-jahani** [comment]
این کتابخونه رو کافه بازار توسعه نداده
کتابخونه اوپن سورس گوگلِ.
فقط چند تا لینک و پکیج رو تغییر دادن.

**Comment by aliakbarmostafaei** [comment]
@remohammadi با سلام. کتابخانه خرید درون برنامه ای گوگل اخیرا بروزرسانی شده و اشکالات مهمی اعم از شرایط رقابت در هنگام کوئری گرفتن از سرور رفع شده همچنین نسخه کاتلین کتابخانه بر پایه معماری جدید ام وی وی ام منتشر شده لطفا رسیدگی بفرمایید.
با تشکر.

**Comment by remohammadi** [comment]
سلام، ممنون از پیغامتون، به دوستان اطلاع می‌دهم.

**Comment by sajaddp** [comment]
<div dir=rtl>
سلام

@remohammadi عزیز به دوستان که اطلاع دادید تصممی هم بابت این موضوع گرفتند؟!

واقعیت این هست که زمان بسیار زیادی از آخرین بروزرسانی داکیومنت و مثال های کافه بازار می گذره و این روزها برای نوشتن حتی یک پکیج ساده اتصال به کافه بازار از طریق `react-native` مشکلات زیادی وجود داره و همه ناچار هستند با وصله و پینه پکیج های چندین سال قبل رو در پروژه استفاده کنند که باعث انواع باگ ها میشه.
درسته که انحصار بازار مارکت اندرویدی ایران در اختیار شماست اما برای اعتبار و آبروی خودتون هم که شده فکری برای این مسائل بردارید. (احترام گذاشتن به توسعه دهنده ها که باعث ایجاد درآمد برای شما می شوند به درک!)
</div>

**Comment by mehrdadmmb2** [comment]
انصافا بازار فقط یوزر داره
و به لحاظ پشتیبانی به شدت ضعیفه 
قوانین مزخرفی داره که تو مواقع لزوم وقتی به نفعشه خیلی راحت نقضش میکنه

**Comment by shayanpourvatan** [comment]
پروژه سمپل پرداخت درون برنامه‌ای بروزرسانی شد، توجه داشته باشید که این پروژه صرفا مثالی برای نحوه‌ی کال کردن  متد‌های پرداخت می‌باشد و از معماری خاصی استفاده نکردیم، در این مثال هم سعی شده است از هیچ دیزاین پترن یا لایبرری خاصی استفاده نشود تا همه‌ی برنامه‌نویسان عزیز با هر سطحی بتوانند از این مثال استفاده کنن. لطفا برای ‫استفاده از پرداخت درون برنامه‌ای کدهای مربوطه را در معماری استفاده شده پروژه خودتان قرار دهید.
