### ISSUE TITLE
مشکل روی شیائومی

### ISSUE THREAD

**Issue by alleece** [cafebazaar/TrivialDrive#17]
روی گوشی های شیائومی مثل ردمی 7 با کلیک روی خرید فوری برمیگردد و ناموفق است.

**Comment by aliakbarmostafaei** [comment]
> روی گوشی های شیائومی مثل ردمی 7 با کلیک روی خرید فوری برمیگردد و ناموفق است.

احتمالا مشکل مطرح شده در [اینجاست](https://github.com/cafebazaar/TrivialDrive/issues/13#issuecomment-471341769)
برخی برند ها با تنظیمات ذخیره نیرو موجب بسته شدن سرویس های پس زمینه برنامه می شوند که شامل سرویس بازار نیز میشود.

**Comment by alleece** [comment]
این مورد ظاهرا به مجوز خرید بازار ربط دارد که در تنظیمات شیائومی به صورت پیش فرض غیرفعال می شود. البته این مشکل روی دیگر مارکت ها هم رخ می دهد. مطمئن نیستیم به ذخیره نیرو ربط دشات هباشد.

**Comment by shayanpourvatan** [comment]
در ورژن آخر بازار مشکل حل شده است. لطفا فایل‌های‫ AIDL و IABHelper را در پروژه‌ی خود آپدیت کنید ( از درون همین پروژه میتونین اقدام کنید)، در صورتی ‫‪‫‫‫که بازار در گوشی 
کاربر آپدیت باشد دیگر این مشکل رخ نخواهد داد و پرداخت با موفقیت ادامه پیدا می‌کند
