### ISSUE TITLE
null configBundle

### ISSUE THREAD

**Issue by alleece** [cafebazaar/TrivialDrive#22]
خط زیر برای ورژن های قدیمی بازار باعث خطا می شود چون configBundle نال است:  
`Bundle configBundle = mService.getPurchaseConfig(apiVersion, packageName, itemType);
            if (configBundle.getBoolean(INTENT_V2_SUPPORT)) {
                logDebug("launchBuyIntentV2 for " + sku + ", item type: " + itemType);
                launchBuyIntentV2(act, sku, itemType, requestCode, listener, extraData);
            } else {
                logDebug("launchBuyIntent for " + sku + ", item type: " + itemType);
                launchBuyIntent(act, sku, itemType, requestCode, listener, extraData);
            }`

برای کسانی که با ورژن حدید بازار دارند تست می کنند احتمالا مشکل درست می کند.

**Comment by shayanpourvatan** [comment]
شما تو تست‌هاتون به این مضوع برخوردید؟ چون تو تست‌های ما خود او‌اس یک آبجکت خالی بر میگردوند و مشکلی در این زمینه نبود!

**Comment by alleece** [comment]
بله دقیقا نال برمیگشت و میفتاد داخل بلوک Catch
روی نسخه قبلی تر بازار و فکر کنم هواوی p9 lite بود یا نوکیا 3.2

**Comment by shayanpourvatan** [comment]
با تشکر از مطرح کردن مشکل. برطرف گردید.

**Comment by alleece** [comment]
خواهش می کنم.
