### ISSUE TITLE
گوشی شیائومی

### ISSUE THREAD

**Issue by noyanebi** [cafebazaar/TrivialDrive#24]
Bundle configBundle = mService.getPurchaseConfig(apiVersion) ;
configBundle == null mishe
Xiaomi mi 9 
Xiaomi 7 redmi
caffebazar version 8.12.1
سلام تو گوشی های شیائومی هنوز این مشکل وجود داره لطفا راهنمایی کنید
قبلا هم در این مورد تیکت زده شده ولی همچنان به این مشکل برمیخورم
null configBundle #22

**Comment by shayanpourvatan** [comment]
سلام.
مشکلی که قبلا گزارش شده بود برای زمانی بود که ورژن کافه‌بازار قدیمی باشد. این مشکلی که شما میفرمایید با ورژن‌های جدید هست که بعید میدونم اتفاق بیوفته.

فایل آ‌ی‌ای‌دی‌ال خود را آپدیت کرده‌اید؟ 
این مشکل فکنم یک جایی در پیاده‌سازی شما نهفته باشد که با این اطلاعاتی که دادید نمیتوانیم کمک بیشتری بکنیم. لطفا یکبار دیگر مراحل پیاده‌سازی رو مطالعه بفرمایید و مطیین شوید که درست پیاده کرده‌اید. 

باتشکر

**Comment by noyanebi** [comment]
بنظرم مشکل از سمت فایل v3   aidl هستش به اینصورت که دو تا متد جدید که به انتهای فایل v3 aidl  پس از متد consumePurchase  اضافه شده باعث میشه که متدهای aidl v6 google payment از کار بیوفته به این دلیل که فایل aidl  حساس به ترتیب متدها هستش . برای حل این مشکل بهتره که دو تا متد جدید getBuyIntentV2 & getPurchaseConfig به انتهای فایل  aidl v6 google payment  اضافه بشه که هم بتونیم از خرید کافه بازار و هم گوگل پلی به درستی استفاده کنیم

لطفا به این لینک هم نگاه کنید
 https://stackoverflow.com/questions/36170642/what-will-happen-if-the-aidl-files-do-not-match
