### ISSUE TITLE
a bug in incomplete purchase

### ISSUE THREAD

**Issue by bodaghialib4** [cafebazaar/TrivialDrive#25]
hello,

I see a bug in my app that related to the in-app billing of Cafebazaar. so I decided to test in TrivialDrive and see this bug in TrivialDrive also.

If in the step "خرید با موفقیت انجام شد" instead of pressing "باشه" button, close the app, it will be impossible to purchase again or consume that product.

By the way, if I clear data of the CafeBazaar app, in my app this error disappears untile the next incompleted purchase but in TrivialDrive, it crashes the app.

I will be grateful if there is a solution. our app is near to release and we need to fix this problem as soon as possible.

**Comment by shayanpourvatan** [comment]
Hello.

you saw this error As you don't consume the purchase, we can't do anything for this issue as you must do this step in your side for security reason. I think it's not critical issue as user can buy product with repeating purchase scenario without pay any cost.

**Comment by bodaghialib4** [comment]
I checked your code and saw in onCreate (in the listener of mHelper.startSetup section),  it checks owned Items and if there is an item that purchased but not consumed, it tries to consume that item.
but if in the step "خرید با موفقیت انجام شد" instead of pressing "باشه" button, close the app, next time the TrivialDrive crash as it starts up.

**Comment by shayanpourvatan** [comment]
App Crashed because we don't set `base64EncodedPublicKey` in our code,  then you crash in security check, if you set it properly you won't crash in this case.
