### ISSUE TITLE
mContext is null

### ISSUE THREAD

**Issue by behrooz-fard** [cafebazaar/TrivialDrive#27]
I understood that in many devices this error occurred in some place of code. The problem is that MContext returns null.
My IabHelper initializing:

                    if (this.getContext() != null) {
                        mHelper = new IabHelper(this.getContext(), base64EncodedPublicKey);

                        mHelper.startSetup(new IabHelper.OnIabSetupFinishedListener() {
                            public void onIabSetupFinished(IabResult result) {
                                
                                    // list of  all purchases
                                    List additionalSkuList = new ArrayList();
                                    additionalSkuList.add(SKU_UPDATE_AD);
                                    mHelper.queryInventoryAsync(true, additionalSkuList, mGotInventoryListener);
                                }
                            });
                    }

and my crash report is:

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at com.app.mobile.utils.bazarUtils.IabHelper.queryPurchases(IabHelper.java:927)
       at com.app.mobile.utils.bazarUtils.IabHelper.queryInventory(IabHelper.java:650)
       at com.app.mobile.utils.bazarUtils.IabHelper.queryInventory(IabHelper.java:614)
       at com.app.mobile.utils.bazarUtils.IabHelper$2.run(IabHelper.java:713)
       at java.lang.Thread.run(Thread.java:764)

**Comment by shayanpourvatan** [comment]
This issue related to your code completely, I think you create IABHelper instance in fragment class, pass application context to iabHelper will fix your issue, 

PS. Don't forget to dispose iabHelper instance when you don't need it.
